version: "3.9"
services:
  api:
    build: ./api/
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_DEBUG: True
  
  ui:
    build:  ./ui
    ports: [3000:3000]
    volumes:
      - ./ui:/ui
    